export const PERSON = {
  name: 'Ashutosh Suryawanshi',
  headline: 'AI Engineer | Generative AI | RAG Systems | LLM Applications',
  tagline:
    'Fresher AI Engineer specialising in Generative AI, RAG pipelines, and Agentic AI systems. Built production-ready LLM applications achieving 90%+ retrieval accuracy (RAGAS-evaluated) with real observability, deployment, and measurable impact.',
  location: 'Hyderabad, India',
  email: 'ashusurya00@gmail.com',
  phone: '+91 7385645001',
  github: 'https://github.com/Ashusurya00',
  linkedin: 'https://www.linkedin.com/in/ashutosh-suryawanshi-26aa46378/',
  twitter: 'https://x.com/home',
  discord: 'https://discord.com/channels/@me',
  roles: ['AI Engineer', 'GenAI Builder', 'Data Scientist', 'RAG Specialist', 'ML Engineer'],
};

export const STATS = [
  { val: '90%+', label: 'RAG Accuracy' },
  { val: '65%', label: 'Faster Processing' },
  { val: '3+', label: 'Live AI Apps' },
  { val: '4', label: 'Certifications' },
];

export const PROJECTS = [
  {
    slug: 'rag-banking-chatbot',
    title: 'AI Banking RAG Chatbot',
    description: 'RAG-powered banking assistant that answers customer queries using real banking documents. Built with Gemini, LangChain, FAISS vector store, and Streamlit.',
    stack: ['Gemini API', 'LangChain', 'FAISS', 'Streamlit', 'Python', 'RAGAS', 'LangSmith'],
    metrics: [
      { val: '90%+', label: 'Accuracy' },
      { val: '<2s', label: 'Latency' },
    ],
    github: 'https://github.com/Ashusurya00/Generative-ai-banking-chatbot',
    demo: 'https://generative-ai-banking-chatbot-gbjdmmgwpwwel3rerqsgru.streamlit.app/',
    icon: '🏦',
    accent: '#00d4aa',
    featured: true,
  },
  {
    slug: 'ai-resume-analyzer',
    title: 'AI Resume Analyzer',
    description: 'Gemini AI-powered resume analyzer that extracts skills, scores job description matches, and provides actionable improvement feedback via a Streamlit dashboard.',
    stack: ['Gemini API', 'Python', 'Streamlit', 'NLP', 'PDFPlumber'],
    metrics: [
      { val: 'LLM', label: 'Scoring' },
      { val: 'PDF', label: 'Analysis' },
    ],
    github: 'https://github.com/Ashusurya00/AI-resume-analyzer',
    demo: 'https://ai-resume-analyzer-95bnujjzjadh3m46hkhtar.streamlit.app/',
    icon: '📄',
    accent: '#38bdf8',
    featured: true,
  },
  {
    slug: 'multi-agent-system',
    title: 'Multi-Agent AI System',
    description: 'A collaborative multi-agent AI framework where specialized agents (research, coding, review) work together autonomously to solve complex tasks using LangGraph and Gemini.',
    stack: ['LangGraph', 'Gemini API', 'CrewAI', 'LangChain', 'Streamlit', 'Python'],
    metrics: [
      { val: '5', label: 'Agents' },
      { val: '65%', label: 'Efficiency' },
    ],
    github: 'https://github.com/Ashusurya00/Multi-Agent-System',
    demo: 'https://multi-agent-system-4hey2jhs6vzkewdumxu3uy.streamlit.app/',
    icon: '🤖',
    accent: '#a78bfa',
    featured: true,
  },
  {
    slug: 'fraud-detection-system',
    title: 'E2E Fraud Detection System',
    description: 'Real-time fraud detection pipeline using ML models, FastAPI backend, and an interactive Streamlit dashboard for transaction monitoring.',
    stack: ['Python', 'Scikit-learn', 'FastAPI', 'Streamlit', 'Pandas'],
    metrics: [
      { val: 'ML', label: 'Detection' },
      { val: 'Real-time', label: 'API' },
    ],
    github: 'https://github.com/Ashusurya00/end-to-end-fraud-detection-system',
    demo: 'https://end-to-end-fraud-detection-system-ymylinsg7mbeafkganodoa.streamlit.app/',
    icon: '🛡️',
    accent: '#f87171',
    featured: true,
  },
  {
    slug: 'churn-prediction',
    title: 'Customer Churn Prediction',
    description: 'ML-powered customer churn prediction app with Streamlit dashboard, Gemini AI insights, and an end-to-end data science pipeline.',
    stack: ['Python', 'Scikit-learn', 'Gemini API', 'Streamlit', 'Matplotlib'],
    metrics: [
      { val: 'AI', label: 'Insights' },
      { val: 'E2E', label: 'Pipeline' },
    ],
    github: 'https://github.com/Ashusurya00/customer-churn-prediction-',
    demo: 'https://iab9iyk89bxrin67bnvciz.streamlit.app/',
    icon: '📉',
    accent: '#fbbf24',
    featured: true,
  },
  {
    slug: 'recommender-system',
    title: 'AI Recommender System',
    description: 'AI-powered recommender system using collaborative filtering and content-based filtering to deliver personalized suggestions via a Streamlit app.',
    stack: ['Python', 'Scikit-learn', 'Streamlit', 'NLTK', 'Pandas'],
    metrics: [
      { val: 'RecSys', label: 'Model' },
      { val: 'Hybrid', label: 'Filtering' },
    ],
    github: 'https://github.com/Ashusurya00/Recommender-system',
    demo: 'https://recommender-system-kgb3nfdcmndpbmtmjasoqr.streamlit.app/',
    icon: '🎯',
    accent: '#34d399',
    featured: true,
  },
  {
  "slug": "-aionex-agentic-ai-operations-copilot-",
  "title": " AIONEX Agentic AI Operations Copilot ",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/-AIONEX-Agentic-AI-Operations-Copilot-",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "advance-chatbot",
  "title": "advance chatbot",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/advance-chatbot",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "advance-yolo-model",
  "title": "advance Yolo model",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/advance-Yolo-model",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "agentic-ai-codes",
  "title": "agentic ai codes",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/agentic-ai-codes",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "ashusurya00",
  "title": "Ashusurya00",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/Ashusurya00",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "ashutosh-s-portfolio",
  "title": "ashutosh s portfolio",
  "description": "This is my personal portfolio website, highlighting my work as an AI/ML engineer. It features my projects, skills, and achievements in data science, machine learning, and web development. The site is designed to provide a clear and interactive showcase of my professional journey.",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/ashutosh-s-portfolio",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "avacado-price-prediction",
  "title": "avacado_price_prediction",
  "description": "Built a machine learning model to predict avocado prices based on region, year, and type. Performed data cleaning, EDA, and trained models like Linear Regression and Random Forest. Deployed a Flask web app on Render for real-time avocado price prediction and insights.",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/avacado_price_prediction",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "cicd-pipeline",
  "title": "cicd_pipeline",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/cicd_pipeline",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "cnn-bootcamp",
  "title": "CNN bootcamp",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/CNN-bootcamp",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "crypto-currency-prediction",
  "title": "Crypto Currency Prediction",
  "description": "Crypto Currency Analysis & Prediction project performing EDA to uncover trends and patterns, followed by training and comparing multiple ML models for price prediction. Includes data preprocessing, visualization, feature engineering, and model performance evaluation.",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/Crypto-Currency-Prediction",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "cursor-ai",
  "title": "cursor ai",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/cursor-ai",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "fine-tuning-lora-qlora-quantization-bits-floating-",
  "title": "fine tuning lora qlora quantization bits floating ",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/fine-tuning-lora-qlora-quantization-bits-floating-",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "fsds-genai-agenticai-aitools",
  "title": "fsds genai agenticai aitools",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/fsds-genai-agenticai-aitools",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "google-antigravity-ide-",
  "title": "google antigravity ide ",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/google-antigravity-ide-",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "health-care-prediction-",
  "title": "Health_care_prediction ",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/Health_care_prediction-",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "image-generation-model",
  "title": "Image_generation_model",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/Image_generation_model",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "langchain-codes",
  "title": "langchain codes",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/langchain-codes",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "langgraph-codes",
  "title": "langgraph codes",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/langgraph-codes",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "mediapipe-codes",
  "title": "mediapipe codes",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/mediapipe-codes",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "ml-playground",
  "title": "ml playground",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/ml-playground",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "ml-models",
  "title": "ML_models",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/ML_models",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "multimodel-ai",
  "title": "multimodel AI",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/multimodel-AI",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "multiple-object-detection",
  "title": "Multiple_object_detection",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/Multiple_object_detection",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "multi-lang-translator",
  "title": "multi_lang_translator",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/multi_lang_translator",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "my-own-agentic-ide",
  "title": "my own agentic ide",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/my-own-agentic-ide",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "nlp-codes",
  "title": "NLP_codes",
  "description": "A comprehensive collection of Natural Language Processing (NLP) techniques and models covering text preprocessing, tokenization, lemmatization, feature extraction (BoW, TF-IDF, Word2Vec), and modern deep learning methods for text understanding, classification, and generation tasks.",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/NLP_codes",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "ollama-models",
  "title": "ollama models",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/ollama-models",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "portfolio-redifined",
  "title": "portfolio redifined",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/portfolio-redifined",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "portfolio-redifined2",
  "title": "portfolio redifined2",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/portfolio-redifined2",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "promt-to-image-generation",
  "title": "promt to image generation",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/promt-to-image-generation",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "python-memory",
  "title": "python memory",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/python-memory",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "voice-assistant-",
  "title": "voice assistant ",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/voice-assistant-",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
},
  {
  "slug": "yolo-model-for-object-detection",
  "title": "yolo model for object detection",
  "description": "GitHub Repository",
  "stack": [],
  "metrics": [],
  "github": "https://github.com/Ashusurya00/yolo-model-for-object-detection",
  "demo": null,
  "icon": "📁",
  "accent": "#94a3b8",
  "featured": false
}
];

export const SKILLS = [
  {
    category: 'Generative AI / LLMs',
    icon: '🧠',
    items: [
      { name: 'LangChain', level: 'expert' },
      { name: 'LlamaIndex', level: 'expert' },
      { name: 'RAG Pipelines', level: 'expert' },
      { name: 'OpenAI API', level: 'expert' },
      { name: 'Gemini API', level: 'expert' },
      { name: 'HuggingFace', level: 'expert' },
      { name: 'LangSmith', level: 'expert' },
      { name: 'RAGAS', level: 'expert' },
      { name: 'FAISS', level: 'expert' },
      { name: 'Pinecone', level: 'proficient' },
      { name: 'ChromaDB', level: 'proficient' },
      { name: 'Weaviate', level: 'familiar' },
    ],
  },
  {
    category: 'Agentic AI',
    icon: '🤖',
    items: [
      { name: 'CrewAI', level: 'expert' },
      { name: 'LangGraph', level: 'expert' },
      { name: 'AutoGen', level: 'proficient' },
      { name: 'Multi-Agent Systems', level: 'expert' },
      { name: 'Tool Calling', level: 'expert' },
      { name: 'Agent Memory', level: 'proficient' },
    ],
  },
  {
    category: 'AI / Machine Learning',
    icon: '⚙️',
    items: [
      { name: 'Python', level: 'expert' },
      { name: 'PyTorch', level: 'expert' },
      { name: 'Scikit-learn', level: 'expert' },
      { name: 'TensorFlow', level: 'proficient' },
      { name: 'NLP', level: 'expert' },
      { name: 'Computer Vision', level: 'proficient' },
      { name: 'LoRA / PEFT', level: 'familiar' },
      { name: 'RLHF', level: 'familiar' },
    ],
  },
  {
    category: 'Data Science & Analytics',
    icon: '📊',
    items: [
      { name: 'Pandas', level: 'expert' },
      { name: 'NumPy', level: 'expert' },
      { name: 'EDA', level: 'expert' },
      { name: 'Feature Engineering', level: 'expert' },
      { name: 'SQL', level: 'expert' },
      { name: 'Statistical Analysis', level: 'proficient' },
    ],
  },
  {
    category: 'Data Visualization',
    icon: '📈',
    items: [
      { name: 'Power BI', level: 'expert' },
      { name: 'Matplotlib', level: 'expert' },
      { name: 'Seaborn', level: 'expert' },
      { name: 'Tableau', level: 'proficient' },
      { name: 'Plotly', level: 'proficient' },
    ],
  },
  {
    category: 'Data Engineering',
    icon: '🔧',
    items: [
      { name: 'Kafka', level: 'proficient' },
      { name: 'Airflow', level: 'proficient' },
      { name: 'ETL Pipelines', level: 'proficient' },
      { name: 'DVC', level: 'familiar' },
      { name: 'MLflow', level: 'proficient' },
    ],
  },
  {
    category: 'Cloud & DevOps',
    icon: '☁️',
    items: [
      { name: 'AWS', level: 'proficient' },
      { name: 'GCP', level: 'proficient' },
      { name: 'Azure', level: 'proficient' },
      { name: 'Docker', level: 'expert' },
      { name: 'Kubernetes', level: 'proficient' },
      { name: 'CI/CD', level: 'proficient' },
    ],
  },
  {
    category: 'APIs & Deployment',
    icon: '🚀',
    items: [
      { name: 'FastAPI', level: 'expert' },
      { name: 'Streamlit', level: 'expert' },
      { name: 'Gradio', level: 'proficient' },
      { name: 'REST APIs', level: 'expert' },
    ],
  },
];

export const EXPERIENCE = [
  {
    role: 'Data Science Intern',
    company: 'SaiKet Systems',
    type: 'B2B Analytics Platform',
    bullets: [
      'Built 3 ML models achieving up to 85% accuracy using Scikit-learn',
      'Evaluated models using ROC-AUC and F1-score metrics',
      'Automated reporting workflows reducing manual effort by 60%',
      'Developed Power BI dashboards tracking 5+ KPIs for business insights',
    ],
  },
  {
    role: 'Data Analyst Intern',
    company: 'Codveda',
    type: 'Data Services Company',
    bullets: [
      'Performed EDA on 20K+ records identifying key business trends',
      'Reduced reporting time from 4 hours to 20 minutes using automation',
      'Built analytics dashboards and automated data pipelines',
      'Improved data quality improving downstream ML model performance by 12%',
    ],
  },
];

export const CERTIFICATIONS = [
  { name: 'Generative AI & LLMs', issuer: 'OpenAI Academy', year: '2026' },
  { name: 'Full Stack Data Science', issuer: 'Naresh IT', year: '2026' },
  { name: 'Data Science Mentorship', issuer: 'CampusX', year: '2026' },
  { name: 'Full Stack Development', issuer: 'Internshala', year: '2024' },
];

export const ACHIEVEMENTS = [
  { icon: '🏆', text: 'Winner — Code Debugging Contest, College Tech Fest 2024 (100+ participants)' },
  { icon: '🥉', text: 'Top 3 — AI Hackathon, Inter-college Hackathon 2024 (50+ teams)' },
  { icon: '🤖', text: 'Recognised for AI Automation Innovation' },
];

export const MARQUEE_SKILLS = [
  'LangChain', 'LlamaIndex', 'RAG', 'CrewAI', 'LangGraph',
  'FAISS', 'PyTorch', 'LangSmith', 'RAGAS', 'FastAPI',
  'Docker', 'AWS', 'OpenAI API', 'HuggingFace', 'MLflow', 'Pinecone',
];
